spring:
  application:
    name: employee-service
  jpa:
    hibernate:
      ddl-auto: none
  datasource:  
    url: jdbc:mysql://localhost:3306/employee_database
    username: springstudent
    password: springstudent
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      default-zone: http://localhost:8761/eureka
    
server:
  port: 8100
  

    